### ISSUE TITLE
Normalization for the ionization form factor

### ISSUE THREAD

**Issue by hongwanliu** [temken/obscura#37]
Hi Timon, 

Thank you for making this code public, it is extremely useful for newcomers to direct detection. I had some basic questions regarding the ionization form factor: 1) when calculating the total ionization rate, how are these form factors normalized? In other words, after I integrate over them, do I need to multiply by (2l+1) or 2(2l+1) to account for multiple electrons in each shell? 2) I don't get agreement between your Xe form factors and the nonrelativistic Xe form factors shown in https://arxiv.org/abs/2006.14521 Fig. 15 (left). I was able to produce the blue 5p curve using the QEDark code by Tien-Tien Yu and collaborators, but it looks very different from your result. Should I be surprised?

Thanks for your help!

Hongwan Liu

**Comment by temken** [comment]
Hi Hongwan,

Thanks for opening this issue and your kind words!

Your questions are not obscura-specific in that sense, as the ionization form factors are imported from tables. By default, the ionization form factor used have been tabulated with [DarkARC](https://github.com/temken/DarkARC). Therefore the answers are regarding that code rather than obscura. It is straight forward to import other ionization form factors into obscura.

> 1) when calculating the total ionization rate, how are these form factors normalized? In other words, after I integrate over them, do I need to multiply by (2l+1) or 2(2l+1) to account for multiple electrons in each shell? 

No, this is accounted for. See e.g. eqs. (35) of [the DarkARC paper](https://arxiv.org/abs/1912.08204).

> 2) I don't get agreement between your Xe form factors and the nonrelativistic Xe form factors shown in https://arxiv.org/abs/2006.14521 Fig. 15 (left). I was able to produce the blue 5p curve using the QEDark code by Tien-Tien Yu and collaborators, but it looks very different from your result. Should I be surprised?

You should not be surprised that they are different. They treat the final state wave function differently than we did in DarkARC. If I recall correctly, we ran some comparisons and did not find large deviations in those cases. How much disagreement between Yu et al and DarkARC do you find?

Best regards,
Timon

**Comment by temken** [comment]
Hi Hongwan,

Yes, you stumbled upon an issue with the DarkARC code that I have been fixing, but the fix is not published yet. DarkARC has a flaw that it only sums up the final state quantum number l' up to 7 or so and it doesn't check that the sum (that formally goes to infinity) has in fact converged. Especially around the peak l`<7 is insufficient. Since the python tool DarkARC was too slow and the design was fundamentally flawed, I re-wrote DarkARC into C++ (DarkARC++) which I will publish before the end of the year. If I compare the result from 2006.14521 to the updated DarkARC++ result, I get the following:

<img width="360" alt="Comparsion" src="https://user-images.githubusercontent.com/29034913/145541332-142677db-2855-4f04-82f1-c6f2a6069c48.png">

As you can see, the peak agrees very well now. There are still the same discrepancies for low and high q (where the original DarkARC worked well, so nothing changed there). The discrepancies there must come from the different modelling of the final state wavefunctions. This is something I would like to check at some point.

At this point we model the final state wavefunction as described in our paper [1912.08204](https://arxiv.org/abs/1912.08204). (We didn't come up with this approach, but took it from [1802.06998](https://arxiv.org/abs/1802.06998)).

Best,
Timon

**Comment by hongwanliu** [comment]
Hi Timon, 

Great, good to know! Thanks for looking into it, and I'm looking forward to DarkARC++!

Best, 

Hongwan
